language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  sudo easy_install -q pyzmq
  sudo apt-get install vim-nox ipython

script: |
  vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=.
  set rtp+=after
  filetype plugin indent on
  VIMRC) -c 'Vader! test/*'
  # > /dev/null
